// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	systemUsersFieldNames          = builder.RawFieldNames(&SystemUsers{}, true)
	systemUsersRows                = strings.Join(systemUsersFieldNames, ",")
	systemUsersRowsExpectAutoSet   = strings.Join(stringx.Remove(systemUsersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	systemUsersRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(systemUsersFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	systemUsersModel interface {
		Insert(ctx context.Context, data *SystemUsers) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SystemUsers, error)
		FindOneByMobile(ctx context.Context, mobile string) (*SystemUsers, error)
		FindOneByUsername(ctx context.Context, username string) (*SystemUsers, error)
		Update(ctx context.Context, data *SystemUsers) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSystemUsersModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SystemUsers struct {
		Id           int64         `db:"id"`            // 用户ID
		Username     string        `db:"username"`      // 用户账号
		Password     string        `db:"password"`      // 加密密码(BCrypt)
		Nickname     string        `db:"nickname"`      // 用户昵称
		Mobile       string        `db:"mobile"`        // 手机号码
		Email        string        `db:"email"`         // 用户邮箱
		Avatar       string        `db:"avatar"`        // 头像地址
		Sex          int64         `db:"sex"`           // 用户性别(0未知 1男 2女)
		DeptId       sql.NullInt64 `db:"dept_id"`       // 部门ID
		PostIds      string        `db:"post_ids"`      // 岗位编号数组
		Status       int64         `db:"status"`        // 帐号状态(0正常 1停用)
		Deleted      int64         `db:"deleted"`       // 逻辑删除(0存在 1删除)
		LoginIp      string        `db:"login_ip"`      // 最后登录IP
		LoginDate    sql.NullTime  `db:"login_date"`    // 最后登录时间
		LoginBrowser string        `db:"login_browser"` // 最后登录浏览器类型
		LoginOs      string        `db:"login_os"`      // 最后登录操作系统
		Remark       string        `db:"remark"`        // 备注
		Creator      string        `db:"creator"`       // 创建者
		CreateTime   time.Time     `db:"create_time"`   // 创建时间
		Updater      string        `db:"updater"`       // 更新者
		UpdateTime   time.Time     `db:"update_time"`   // 更新时间
	}
)

func newSystemUsersModel(conn sqlx.SqlConn) *defaultSystemUsersModel {
	return &defaultSystemUsersModel{
		conn:  conn,
		table: `"public"."system_users"`,
	}
}

func (m *defaultSystemUsersModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSystemUsersModel) FindOne(ctx context.Context, id int64) (*SystemUsers, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", systemUsersRows, m.table)
	var resp SystemUsers
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemUsersModel) FindOneByMobile(ctx context.Context, mobile string) (*SystemUsers, error) {
	var resp SystemUsers
	query := fmt.Sprintf("select %s from %s where mobile = $1 limit 1", systemUsersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, mobile)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemUsersModel) FindOneByUsername(ctx context.Context, username string) (*SystemUsers, error) {
	var resp SystemUsers
	query := fmt.Sprintf("select %s from %s where username = $1 limit 1", systemUsersRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, username)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSystemUsersModel) Insert(ctx context.Context, data *SystemUsers) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17, $18)", m.table, systemUsersRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Username, data.Password, data.Nickname, data.Mobile, data.Email, data.Avatar, data.Sex, data.DeptId, data.PostIds, data.Status, data.Deleted, data.LoginIp, data.LoginDate, data.LoginBrowser, data.LoginOs, data.Remark, data.Creator, data.Updater)
	return ret, err
}

func (m *defaultSystemUsersModel) Update(ctx context.Context, newData *SystemUsers) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, systemUsersRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.Username, newData.Password, newData.Nickname, newData.Mobile, newData.Email, newData.Avatar, newData.Sex, newData.DeptId, newData.PostIds, newData.Status, newData.Deleted, newData.LoginIp, newData.LoginDate, newData.LoginBrowser, newData.LoginOs, newData.Remark, newData.Creator, newData.Updater)
	return err
}

func (m *defaultSystemUsersModel) tableName() string {
	return m.table
}
