// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package handler

import (
	"net/http"

	user "github.com/ai4energy/Ai4EEMS-go/app/usercenter/cmd/api/internal/handler/user"
	"github.com/ai4energy/Ai4EEMS-go/app/usercenter/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 用户登录
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: user.LoginHandler(serverCtx),
			},
			{
				// OAuth2 授权端点 (第一步: 请求授权码)
				Method:  http.MethodGet,
				Path:    "/user/oauth/authorize",
				Handler: user.OauthAuthorizeHandler(serverCtx),
			},
			{
				// OAuth2 令牌端点 (第二步: 用授权码换取访问令牌)
				Method:  http.MethodPost,
				Path:    "/user/oauth/token",
				Handler: user.OauthTokenHandler(serverCtx),
			},
			{
				// 用户注册
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: user.RegisterHandler(serverCtx),
			},
		},
		rest.WithPrefix("/usercenter/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 获取当前登录用户的详细信息
				Method:  http.MethodPost,
				Path:    "/user/detail",
				Handler: user.DetailHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/usercenter/v1"),
	)
}
