// Code generated by goctl. DO NOT EDIT.
package types

type CoolPropPureFluidRequest struct {
	Fluid           string  `json:"fluid"`           // 流体的名称，例如 "Ammonia"
	InputParameter1 string  `json:"inputparameter1"` // 输入参数1的类型，例如 "Pressure [Pa]"
	Inputvalue1     float64 `json:"inputvalue1"`     // 输入参数1的值，例如 101325
	InputParameter2 string  `json:"inputparameter2"` // 输入参数2的类型，例如 "Temperature [K]"
	Inputvalue2     float64 `json:"inputvalue2"`     // 输入参数2的值，例如 298
	UnitSystem      string  `json:"unitsystem"`      // 输出单位系统，例如 "Mass-based"
}

type CoolPropPureFluidResponse struct {
	Fluid        string  `json:"fluid"`        // 流体名称
	Temperature  float64 `json:"temperature"`  // 温度 [K]
	Pressure     float64 `json:"pressure"`     // 压力 [Pa]
	VaporQuality float64 `json:"vaporquality"` // 汽化质量分数
	SpeedOfSound float64 `json:"speedofsound"` // 声速 [m/s]
	Density      float64 `json:"density"`      // 密度 [kg/m^3]
	Enthalpy     float64 `json:"enthalpy"`     // 焓 [J/kg]
	Entropy      float64 `json:"entropy"`      // 熵 [J/kg/K]
	Cp           float64 `json:"cp"`           // 定压比热 [J/kg/K]
	Cv           float64 `json:"cv"`           // 定容比热 [J/kg/K]
	UnitSystem   string  `json:"unitsystem"`   // 输出单位系统
}

type PingResponse struct {
	Message string `json:"message"` // 返回的消息内容，例如 "pong"
	Code    int    `json:"code"`    // HTTP 状态码，例如 200
}
