// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	mediaprop "github.com/ai4energy/Ai4EEMS-go/app/mediaprop/cmd/api/internal/handler/mediaprop"
	"github.com/ai4energy/Ai4EEMS-go/app/mediaprop/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// Ping用于健康检查
				Method:  http.MethodGet,
				Path:    "/ping",
				Handler: pingHandler(serverCtx),
			},
		},
		rest.WithTimeout(5000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 计算纯工质物性
				Method:  http.MethodPost,
				Path:    "/purefluid",
				Handler: mediaprop.CalculatePureFluidPropHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
		rest.WithTimeout(5000*time.Millisecond),
		rest.WithMaxBytes(1048576),
	)
}
