// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{}, true)
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	userRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(userFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	userModel interface {
		Insert(ctx context.Context, data *User) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*User, error)
		FindOneByEmail(ctx context.Context, email sql.NullString) (*User, error)
		FindOneByLoginName(ctx context.Context, loginName string) (*User, error)
		FindOneByMobile(ctx context.Context, mobile sql.NullString) (*User, error)
		Update(ctx context.Context, data *User) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	User struct {
		Id          int64          `db:"id"`
		LoginName   string         `db:"login_name"`   // 登录名
		RealName    sql.NullString `db:"real_name"`    // 真实姓名
		Password    string         `db:"password"`     // 密码
		Mobile      sql.NullString `db:"mobile"`       // 手机号
		Email       sql.NullString `db:"email"`        // 邮箱
		Avatar      sql.NullString `db:"avatar"`       // 头像地址
		Status      int64          `db:"status"`       // 状态 0:未启用 1:正常
		CreatedTime time.Time      `db:"created_time"` // 创建时间
		UpdatedTime time.Time      `db:"updated_time"` // 更新时间
		DeletedTime sql.NullTime   `db:"deleted_time"` // 删除时间
		Remark      sql.NullString `db:"remark"`       // 备注
	}
)

func newUserModel(conn sqlx.SqlConn) *defaultUserModel {
	return &defaultUserModel{
		conn:  conn,
		table: `"public"."user"`,
	}
}

func (m *defaultUserModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserModel) FindOne(ctx context.Context, id int64) (*User, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", userRows, m.table)
	var resp User
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByEmail(ctx context.Context, email sql.NullString) (*User, error) {
	var resp User
	query := fmt.Sprintf("select %s from %s where email = $1 limit 1", userRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, email)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByLoginName(ctx context.Context, loginName string) (*User, error) {
	var resp User
	query := fmt.Sprintf("select %s from %s where login_name = $1 limit 1", userRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, loginName)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) FindOneByMobile(ctx context.Context, mobile sql.NullString) (*User, error) {
	var resp User
	query := fmt.Sprintf("select %s from %s where mobile = $1 limit 1", userRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, mobile)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)", m.table, userRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.LoginName, data.RealName, data.Password, data.Mobile, data.Email, data.Avatar, data.Status, data.CreatedTime, data.UpdatedTime, data.DeletedTime, data.Remark)
	return ret, err
}

func (m *defaultUserModel) Update(ctx context.Context, newData *User) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, userRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.LoginName, newData.RealName, newData.Password, newData.Mobile, newData.Email, newData.Avatar, newData.Status, newData.CreatedTime, newData.UpdatedTime, newData.DeletedTime, newData.Remark)
	return err
}

func (m *defaultUserModel) tableName() string {
	return m.table
}
