// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type LongResp struct {
	Id int64 `json:"id"`
}

type UserCreateReq struct {
	Username string   `json:"username"`         // 用户账号
	Password string   `json:"password"`         // 密码 (新增必填)
	Nickname string   `json:"nickname"`         // 用户昵称
	Remark   string   `json:"remark,optional"`  // 备注
	DeptId   uint64   `json:"deptId,optional"`  // 部门ID
	PostIds  []uint64 `json:"postIds,optional"` // 岗位ID数组
	Email    string   `json:"email,optional"`   // 邮箱
	Mobile   string   `json:"mobile,optional"`  // 手机号
	Sex      int32    `json:"sex,optional"`     // 性别
	Avatar   string   `json:"avatar,optional"`  // 头像
	Status   int32    `json:"status"`           // 状态
}

type UserCreateResp struct {
	Id         uint64 `json:"id"`         // 新增用户编号
	CreateTime int64  `json:"createTime"` // 创建时间戳
}

type UserResp struct {
	Id         uint64   `json:"id"`
	Username   string   `json:"username"`
	Nickname   string   `json:"nickname"`
	Remark     string   `json:"remark"`
	DeptId     uint64   `json:"deptId"`
	DeptName   string   `json:"deptName"`
	PostIds    []uint64 `json:"postIds"`
	Email      string   `json:"email"`
	Mobile     string   `json:"mobile"`
	Sex        int32    `json:"sex"`
	Avatar     string   `json:"avatar"`
	Status     int32    `json:"status"`
	LoginIp    string   `json:"loginIp"`
	LoginDate  int64    `json:"loginDate"` // Go 中通常使用时间戳(秒/毫秒)
	CreateTime int64    `json:"createTime"`
}

type UserUpdateReq struct {
	Id       uint64   `json:"id"`               // 用户编号 (必填)
	Username string   `json:"username"`         // 用户账号
	Nickname string   `json:"nickname"`         // 用户昵称
	Remark   string   `json:"remark,optional"`  // 备注
	DeptId   uint64   `json:"deptId,optional"`  // 部门ID
	PostIds  []uint64 `json:"postIds,optional"` // 岗位ID数组
	Email    string   `json:"email,optional"`   // 邮箱
	Mobile   string   `json:"mobile,optional"`  // 手机号
	Sex      int32    `json:"sex,optional"`     // 性别
	Avatar   string   `json:"avatar,optional"`  // 头像
	Status   int32    `json:"status"`           // 状态
}
